repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.5
    hooks:
      # Run the linter.
      - id: ruff
        args:
         - --fix
         - --line-length=120
         - '--per-file-ignores=*/__init__.py:F401'
      # Run the formatter.
      - id: ruff-format
        args:
         - --line-length=120